# Generated by Django 5.2 on 2025-04-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchClock', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
