# Generated by Django 5.2 on 2025-05-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchClock', '0008_companysettings_rest_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='rest_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
    ]
