# Generated by Django 5.2 on 2025-05-02 05:37

from django.db import migrations, models
import django.db.models.deletion


def forward_department_conversion(apps, schema_editor):
    """
    Convert department string values to Department model references
    """
    # Get the models
    Employee = apps.get_model('PunchClock', 'Employee')
    Department = apps.get_model('PunchClock', 'Department')
    
    # Get all unique department values from existing employees
    department_names = set()
    for employee in Employee.objects.all():
        if employee.department and employee.department.strip():
            department_names.add(employee.department.strip())
    
    # Create Department objects for each unique department name
    department_mapping = {}
    for name in department_names:
        department, created = Department.objects.get_or_create(name=name)
        department_mapping[name] = department
    
    # Add a temporary field to store the department ID
    # We'll use this in the next migration to set the proper ForeignKey


class Migration(migrations.Migration):

    dependencies = [
        ('PunchClock', '0010_department_alter_employee_department'),
    ]

    operations = [
        # First run the data migration to create departments
        migrations.RunPython(
            forward_department_conversion,
            migrations.RunPython.noop
        ),
        
        # Add a temporary department reference field
        migrations.AddField(
            model_name='employee',
            name='department_id_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PunchClock.department'),
        ),
    ]
