# Generated by Django 5.2 on 2025-05-02 06:xx

from django.db import migrations, models
import django.db.models.deletion


def link_departments_to_employees(apps, schema_editor):
    """
    Link Department objects to employees using the temporary field
    """
    # Get the models
    Employee = apps.get_model('PunchClock', 'Employee')
    Department = apps.get_model('PunchClock', 'Department')
    
    # Link each employee to the appropriate Department
    for employee in Employee.objects.all():
        if employee.department and employee.department.strip():
            dept_name = employee.department.strip()
            try:
                dept = Department.objects.get(name=dept_name)
                employee.department_id_new = dept
                employee.save(update_fields=['department_id_new'])
            except Department.DoesNotExist:
                # Create it if it doesn't exist (shouldn't happen, but just in case)
                dept = Department.objects.create(name=dept_name)
                employee.department_id_new = dept
                employee.save(update_fields=['department_id_new'])


class Migration(migrations.Migration):
    atomic = False  # Disable transaction for this migration
    
    dependencies = [
        ('PunchClock', '0011_convert_department_strings_to_models'),
    ]
    
    operations = [
        # Link departments to employees
        migrations.RunPython(
            link_departments_to_employees,
            migrations.RunPython.noop
        ),
        
        # Remove the old department CharField in its own operation
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        
        # Rename the new field to 'department' in its own operation
        migrations.RenameField(
            model_name='employee',
            old_name='department_id_new',
            new_name='department',
        ),
    ]
