# Generated by Django 5.2.1 on 2025-05-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchClock', '0013_alter_employee_department_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
