# Generated by Django 5.2.1 on 2025-05-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchClock', '0014_companysettings_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='segment_index',
            field=models.IntegerField(default=0, help_text='Index of this segment for multi-segment workdays'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='session_id',
            field=models.CharField(blank=True, help_text='Client-side session ID to prevent manipulation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='session_verified',
            field=models.BooleanField(default=False, help_text='Whether the session has been verified on the server'),
        ),
    ]
