# Generated by Django 4.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchClock', '0015_timeentry_segment_index_timeentry_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='entry_type',
            field=models.CharField(
                choices=[
                    ('Regular Work Hours', 'Regular Work Hours'),
                    ('Overtime', 'Overtime'),
                    ('Meeting', 'Meeting'),
                    ('Training', 'Training'),
                    ('Other', 'Other'),
                ],
                default='Regular Work Hours',
                max_length=50
            ),
        ),
    ]
